#### Load TensorFlow

In [1]:
import tensorflow as tf
tf.__version__

'2.9.2'

#### Load Data

In [2]:
#Load Boston Housing dataset available within tensorflow
(train_x, train_y),(test_X,test_Y) = tf.keras.datasets.boston_housing.load_data(test_split=0)

57026/57026 [==============================] - 0s 3us/step


In [3]:
type(train_x)

numpy.ndarray

In [4]:
#Check how many training examples we have
train_x.shape

(506, 13)

In [5]:
#Labels for our examples
train_y.shape

(506,)

In [6]:
train_x

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [1.83377e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.89610e+02, 1.92000e+00],
       [3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [2.92400e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.40160e+02, 9.81000e+00]])

In [7]:
#Data type of features
train_x.dtype

dtype('float64')

In [8]:
train_x = train_x.astype('float32')
train_y = train_y.astype('float32')

In [9]:
#Data type of features
train_x.dtype

dtype('float32')

In [10]:
train_x[0:5]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00],
       [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
        6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
        2.02000e+01, 3.96900e+02, 8.01000e+00],
       [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
        6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.91430e+02, 1.46500e+01]], dtype=float32)

#### Build Model

Define Weights and Bias

In [11]:
#We are initializing weights and Bias with Zero
w = tf.random.normal(shape=(13,1))
b = tf.zeros(shape=(1))

Metal device set to: Apple M1 Max


2024-02-21 23:40:49.268705: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-21 23:40:49.269204: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [12]:
print(w)

tf.Tensor(
[[-1.3272711 ]
 [ 1.475364  ]
 [-0.56262136]
 [-1.0130478 ]
 [ 0.25053138]
 [-0.7000595 ]
 [ 1.1537246 ]
 [ 0.56306005]
 [-1.0826735 ]
 [-0.18666165]
 [ 1.2223868 ]
 [ 2.1132193 ]
 [-1.4552455 ]], shape=(13, 1), dtype=float32)


In [13]:
w.numpy()

array([[-1.3272711 ],
       [ 1.475364  ],
       [-0.56262136],
       [-1.0130478 ],
       [ 0.25053138],
       [-0.7000595 ],
       [ 1.1537246 ],
       [ 0.56306005],
       [-1.0826735 ],
       [-0.18666165],
       [ 1.2223868 ],
       [ 2.1132193 ],
       [-1.4552455 ]], dtype=float32)

In [14]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

Define a function to calculate prediction

In [15]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

In [16]:
y = prediction(train_x, w, b)

In [17]:
#y

Function to calculate Loss (Mean Squared Error)

In [18]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr) #Average the loss
    
    return avg

In [19]:
cost = loss(train_y, y)

In [20]:
cost

<tf.Tensor: shape=(), dtype=float32, numpy=585163.06>

Function to train the Model

1.   Record all the mathematical steps to calculate Loss. We will record the steps using GradientTape
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate



In [21]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias - Gradient Descent
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

In [22]:
new_w, new_b = train(train_x, train_y, w, b)

In [23]:
new_w

<tf.Tensor: shape=(13, 1), dtype=float32, numpy=
array([[-3.5090706e+01],
       [-1.9773962e+02],
       [-1.4855374e+02],
       [-2.0865510e+00],
       [-7.6134381e+00],
       [-9.3308243e+01],
       [-9.6099652e+02],
       [-5.8693542e+01],
       [-1.1757882e+02],
       [-5.5213887e+03],
       [-2.6598254e+02],
       [-5.6119414e+03],
       [-1.7170079e+02]], dtype=float32)>

In [24]:
new_b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-14.628584], dtype=float32)>

#### Start Training

In [25]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(train_x, train_y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(train_y, prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 19515228000000.0
Current Loss on iteration 1 7.6386165e+20
Current Loss on iteration 2 2.9927681e+28
Current Loss on iteration 3 inf
Current Loss on iteration 4 inf
Current Loss on iteration 5 inf
Current Loss on iteration 6 inf
Current Loss on iteration 7 inf
Current Loss on iteration 8 inf
Current Loss on iteration 9 inf
Current Loss on iteration 10 nan
Current Loss on iteration 11 nan
Current Loss on iteration 12 nan
Current Loss on iteration 13 nan
Current Loss on iteration 14 nan
Current Loss on iteration 15 nan
Current Loss on iteration 16 nan
Current Loss on iteration 17 nan
Current Loss on iteration 18 nan
Current Loss on iteration 19 nan
Current Loss on iteration 20 nan
Current Loss on iteration 21 nan
Current Loss on iteration 22 nan
Current Loss on iteration 23 nan
Current Loss on iteration 24 nan
Current Loss on iteration 25 nan
Current Loss on iteration 26 nan
Current Loss on iteration 27 nan
Current Loss on iteration 28 nan
Current Loss on iter

In [26]:
#Check Weights and Bias
print('Weights:\n', w.numpy())
print('Bias:\n',b.numpy())

Weights:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Bias:
 [nan]


In [27]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ], dtype=float32)