#### Load TensorFlow

In [1]:
import tensorflow as tf
tf.__version__

'2.9.2'

#### Load Data

In [2]:
#Load Boston Housing Dataset
(train_x, train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [3]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [4]:
train_x = train_x.astype('float32')
train_y = train_y.astype('float32')

In [5]:
train_x.shape

(506, 13)

In [6]:
train_y.shape

(506,)

Normalize input features

In [7]:
from sklearn.preprocessing import Normalizer

In [8]:
transformer = Normalizer()
train_x = transformer.fit_transform(train_x)

In [9]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945357, 0.00778265, 0.00782785, 0.6007879 ,
       0.04109624, 0.7767189 , 0.03663436], dtype=float32)

#### Build Model

Define Weights and Bias

In [10]:
#We are initializing weights and Bias with Zero
w = tf.random.normal(shape=(13,1))
b = tf.zeros(shape=(1))

Metal device set to: Apple M1 Max


2024-02-21 23:42:01.387752: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-21 23:42:01.388230: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Define a function to calculate prediction

In [11]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

Function to calculate Loss (Mean Squared Error)

In [12]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate



In [13]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

#### Start Training

In [14]:
for i in range(100):
    
    w, b = train(train_x, train_y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, loss(train_y, 
                                               prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 582.8071
Current Loss on iteration 1 545.1161
Current Loss on iteration 2 510.27744
Current Loss on iteration 3 478.07535
Current Loss on iteration 4 448.31027
Current Loss on iteration 5 420.79776
Current Loss on iteration 6 395.36734
Current Loss on iteration 7 371.86154
Current Loss on iteration 8 350.13452
Current Loss on iteration 9 330.05182
Current Loss on iteration 10 311.48895
Current Loss on iteration 11 294.3308
Current Loss on iteration 12 278.47125
Current Loss on iteration 13 263.81186
Current Loss on iteration 14 250.26186
Current Loss on iteration 15 237.7373
Current Loss on iteration 16 226.16058
Current Loss on iteration 17 215.45996
Current Loss on iteration 18 205.56909
Current Loss on iteration 19 196.42677
Current Loss on iteration 20 187.9763
Current Loss on iteration 21 180.16533
Current Loss on iteration 22 172.94548
Current Loss on iteration 23 166.272
Current Loss on iteration 24 160.10352
Current Loss on iteration 25 154.40184
Cur

In [16]:
#Check Weights and Bias
print('Weights:\n', w.numpy())
print('Bias:\n',b.numpy())

Weights:
 [[ 1.3317236e+00]
 [-1.5965809e-01]
 [ 9.6345782e-02]
 [-3.8291898e-01]
 [ 5.3024715e-01]
 [-5.9402573e-01]
 [ 4.0946002e-03]
 [-7.6564604e-01]
 [ 6.9044702e-02]
 [ 7.9550939e+00]
 [-1.5746429e+00]
 [ 7.2633352e+00]
 [ 9.9591506e-01]]
Bias:
 [11.824347]


In [17]:
for i in range(50):
    
    w, b = train(train_x, train_y, w, b)
    print('Current Loss on iteration', i, loss(train_y, prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 84.935265
Current Loss on iteration 1 84.92058
Current Loss on iteration 2 84.90698
Current Loss on iteration 3 84.89441
Current Loss on iteration 4 84.88275
Current Loss on iteration 5 84.871956
Current Loss on iteration 6 84.86198
Current Loss on iteration 7 84.85271
Current Loss on iteration 8 84.844124
Current Loss on iteration 9 84.83618
Current Loss on iteration 10 84.82881
Current Loss on iteration 11 84.82199
Current Loss on iteration 12 84.81565
Current Loss on iteration 13 84.80978
Current Loss on iteration 14 84.80434
Current Loss on iteration 15 84.79928
Current Loss on iteration 16 84.79459
Current Loss on iteration 17 84.79023
Current Loss on iteration 18 84.78619
Current Loss on iteration 19 84.782425
Current Loss on iteration 20 84.77892
Current Loss on iteration 21 84.77568
Current Loss on iteration 22 84.77265
Current Loss on iteration 23 84.769844
Current Loss on iteration 24 84.76722
Current Loss on iteration 25 84.76478
Current Loss on i