### Load tensorflow

In [23]:
import tensorflow as tf

In [24]:
from sklearn.preprocessing import Normalizer

### Collect Data

In [85]:
(train_x, train_y),(test_x,test_y) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [86]:
#train_x = train_x.astype('float32')
#train_y = train_y.astype('float32')

In [93]:
train_x.shape

(506, 13)

In [94]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [95]:
transformer = Normalizer()
train_x = transformer.fit_transform(train_x)

In [96]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

### Building the graph in Keras

In [97]:
tf.keras.backend.clear_session()

#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(13,)))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the Graph

In [98]:
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 6ms/step - loss: 403.9946
Epoch 2/100
 1/16 [>.............................] - ETA: 0s - loss: 216.2562

2024-03-08 23:33:08.051166: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


16/16 [==============================] - 0s 4ms/step - loss: 172.7920
Epoch 3/100
16/16 [==============================] - 0s 4ms/step - loss: 106.6388
Epoch 4/100
16/16 [==============================] - 0s 4ms/step - loss: 87.2922
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 81.2754
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 78.9911
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 78.0058
Epoch 8/100
16/16 [==============================] - 0s 4ms/step - loss: 77.3692
Epoch 9/100
16/16 [==============================] - 0s 4ms/step - loss: 76.7799
Epoch 10/100
16/16 [==============================] - 0s 4ms/step - loss: 76.2272
Epoch 11/100
16/16 [==============================] - 0s 4ms/step - loss: 75.7372
Epoch 12/100
16/16 [==============================] - 0s 4ms/step - loss: 75.2248
Epoch 13/100
16/16 [==============================] - 0s 4ms/step - loss: 74.8010
Epoch 14/100
16/16 [==============

In [99]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.get_weights()

[array([[-1.8938635e-01],
        [ 4.4921641e+00],
        [-2.9210737e-01],
        [-7.5343281e-02],
        [-5.1798094e-03],
        [ 7.1185298e-02],
        [-1.1460658e+00],
        [ 2.2707877e-01],
        [ 4.2368066e-01],
        [-1.4691578e+00],
        [-2.1162398e-01],
        [ 1.7967115e+01],
        [-1.6184170e+00]], dtype=float32),
 array([11.880854], dtype=float32)]

In [101]:
model.get_weights()

[array([[-1.8938635e-01],
        [ 4.4921641e+00],
        [-2.9210737e-01],
        [-7.5343281e-02],
        [-5.1798094e-03],
        [ 7.1185298e-02],
        [-1.1460658e+00],
        [ 2.2707877e-01],
        [ 4.2368066e-01],
        [-1.4691578e+00],
        [-2.1162398e-01],
        [ 1.7967115e+01],
        [-1.6184170e+00]], dtype=float32),
 array([11.880854], dtype=float32)]

### Save the model

In [102]:
model.save('boston_housing_lr.h5')

In [103]:
!ls -l

total 2368
-rw-r--r--@ 1 vidyadharbendre  staff  529649 Feb 22 00:34 01_linear_vs_non_linear.ipynb
-rw-------@ 1 vidyadharbendre  staff    2821 Feb 25  2022 1. Tensorflow_Hello_World_tf2.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff   90243 Mar  8 10:02 1_Tensorflow_basics.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff    3004 Feb 17 20:50 1_tensorflow.ipynb
-rw-------@ 1 vidyadharbendre  staff   20788 Feb 21 23:41 2a. Boston Housing Prices.ipynb
-rw-------@ 1 vidyadharbendre  staff   16977 Feb 21 23:43 2b. Boston Housing Prices_Normalization.ipynb
-rw-------@ 1 vidyadharbendre  staff   53078 Mar  8 23:31 3. Boston_Housing_Prices_KERAS.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff  366737 Feb 22 16:54 Gradient_Descent_step_by_step.ipynb
-rw-------@ 1 vidyadharbendre  staff   26413 Feb 23 19:48 Regression+-+Boston+housing+prices+-TF2.ipynb
-rw-------@ 1 vidyadharbendre  staff   59126 Feb 23 19:38 Regression_with_tensorflow.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff   15064 Mar  8 23:33 boston_hou

In [104]:
train_x[0].shape

(13,)

In [105]:
train_x[0].shape

(13,)

In [106]:
model.predict(train_x[0])

ValueError: in user code:

    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1845, in predict_function  *
        return step_function(self, iterator)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1834, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1823, in run_step  **
        outputs = model.predict_step(data)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1791, in predict_step
        return self(x, training=False)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/input_spec.py", line 228, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential" (type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received by layer "sequential" (type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=float32)
      • training=False
      • mask=None


In [ ]:
import numpy as np

In [ ]:
input_data = np.expand_dims(train_x[0], axis=0)
input_data.shape

In [107]:
model.predict(input_data)

1/1 [==============================] - 0s 23ms/step


2024-03-08 23:33:15.007125: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[6951.1323]], dtype=float32)

In [108]:
train_y[0]

15.2

In [109]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [110]:
train_y[0:5]

array([15.2, 42.3, 50. , 21.1, 17.7])

In [111]:
input_data = np.expand_dims(train_x[0:3], axis=0)
input_data.shape

(1, 3, 13)

In [112]:
input_data = np.expand_dims(train_x[1], axis=0)
input_data.shape

(1, 13)

In [113]:
model.predict(input_data)

1/1 [==============================] - 0s 13ms/step


array([[24.88352]], dtype=float32)