### Load tensorflow

In [1]:
import tensorflow as tf

In [2]:
from sklearn.preprocessing import Normalizer

### Collect Data

In [3]:
(train_x, train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [4]:
#train_x = train_x.astype('float32')
#train_y = train_y.astype('float32')

In [5]:
train_x.shape

(506, 13)

In [6]:
transformer = Normalizer()
train_x = transformer.fit_transform(train_x)

In [7]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

### Building the graph in Keras

In [8]:
tf.keras.backend.clear_session()

#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(13,)))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

Metal device set to: Apple M1 Max


2024-02-21 23:43:04.970583: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-21 23:43:04.970870: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


### Execute the Graph

In [9]:
model.fit(train_x, train_y, epochs=100)

Epoch 1/100


2024-02-21 23:43:10.453641: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2024-02-21 23:43:10.534813: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


16/16 [==============================] - 1s 15ms/step - loss: 405.5366
Epoch 2/100
16/16 [==============================] - 0s 4ms/step - loss: 172.8186
Epoch 3/100
16/16 [==============================] - 0s 4ms/step - loss: 105.8908
Epoch 4/100
16/16 [==============================] - 0s 4ms/step - loss: 86.8275
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 81.1615
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 79.0497
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 78.0317
Epoch 8/100
16/16 [==============================] - 0s 4ms/step - loss: 77.3685
Epoch 9/100
16/16 [==============================] - 0s 4ms/step - loss: 76.7862
Epoch 10/100
16/16 [==============================] - 0s 4ms/step - loss: 76.2626
Epoch 11/100
16/16 [==============================] - 0s 4ms/step - loss: 75.7846
Epoch 12/100
16/16 [==============================] - 0s 4ms/step - loss: 75.3347
Epoch 13/100
16/16 [=============

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.get_weights()

[array([[-0.17270234],
        [ 3.603731  ],
        [-0.47684094],
        [ 0.0850628 ],
        [-0.62710655],
        [-0.14087899],
        [-0.7238508 ],
        [ 0.69766915],
        [-0.52253234],
        [-1.5927249 ],
        [ 0.6278631 ],
        [17.90557   ],
        [-1.1662514 ]], dtype=float32),
 array([11.890104], dtype=float32)]

In [12]:
model.get_weights()

[array([[-0.17270234],
        [ 3.603731  ],
        [-0.47684094],
        [ 0.0850628 ],
        [-0.62710655],
        [-0.14087899],
        [-0.7238508 ],
        [ 0.69766915],
        [-0.52253234],
        [-1.5927249 ],
        [ 0.6278631 ],
        [17.90557   ],
        [-1.1662514 ]], dtype=float32),
 array([11.890104], dtype=float32)]

### Save the model

In [13]:
model.save('boston_housing_lr.h5')

In [14]:
!ls -l

total 18112
-rw-r--r--@ 1 vidyadharbendre  staff   347420 Feb 17 07:05 01_linear_vs_non_linear.ipynb
-rw-------@ 1 vidyadharbendre  staff     2821 Feb 25  2022 1. Tensorflow_Hello_World_tf2.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff   102458 Feb 20 10:31 1_Tensorflow_basics.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff     3004 Feb 17 20:50 1_tensorflow.ipynb
-rw-------@ 1 vidyadharbendre  staff    20788 Feb 21 23:41 2a. Boston Housing Prices.ipynb
-rw-------@ 1 vidyadharbendre  staff    16977 Feb 21 23:43 2b. Boston Housing Prices_Normalization.ipynb
-rw-------@ 1 vidyadharbendre  staff     3750 Feb 25  2022 3. Boston_Housing_Prices_KERAS.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff  6357942 Feb 20 10:31 Session1.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff  2349318 Feb 21 23:08 Session2.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff    29859 Feb 20 10:29 Untitled.ipynb
-rw-r--r--@ 1 vidyadharbendre  staff    15064 Feb 21 23:43 boston_housing_lr.h5


In [15]:
train_x[0].shape

(13,)

In [16]:
model.predict(train_x[0])

ValueError: in user code:

    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1845, in predict_function  *
        return step_function(self, iterator)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1834, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1823, in run_step  **
        outputs = model.predict_step(data)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/training.py", line 1791, in predict_step
        return self(x, training=False)
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/vidyadharbendre/miniforge3/lib/python3.9/site-packages/keras/engine/input_spec.py", line 228, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential" (type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received by layer "sequential" (type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=float32)
      • training=False
      • mask=None


In [17]:
import numpy as np

In [18]:
input_data = np.expand_dims(train_x[0], axis=0)
input_data.shape

(1, 13)

In [19]:
model.predict(input_data)

1/1 [==============================] - 0s 116ms/step


2024-02-21 23:44:10.978143: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[24.684963]], dtype=float32)

In [20]:
train_y[0]

15.2